---
language: ruby
bundler_args: --without debugger docs production --deployment --jobs=3 --retry=3
before_install:
  - sudo apt-get install libicu-dev
install: bin/cached-bundle $TRAVIS_REPO_SLUG
before_script:
  - bin/rake db:create RAILS_ENV=test
script:
  - bin/rake lint
  - bin/rake spec:unit spec:features
  - bin/rake spec:javascripts
env:
  global:
    # AWS_ACCESS_KEY_ID for bin/cached-bundle
    - secure: T9HRgMWl4+F9n5Q8nVjT8dWkjjCfOhBhPmPcjtvddVFfJhe4znp3zaHWOiec7kBL4iXvhCMj+X6vJmgUygOT3H6m26z6RdZCmcM4nA6CE8P8O41KglRysEBLb8WiYWZCWZL/tHIMKawG50rm2vVBZ2Mr9slZ4JTNpuBDHnWHTkc=

    # AWS_SECRET_ACCESS_KEY for bin/cached-bundle
    - secure: EtL4W4oxPnvFE1EXx9M+y5xgFIP34QfPLkEhxz+KBx2f/kDW9aFhpJbhaIU+UiF51g/1JmIf7SyEER3Ah69rAcYxdMWSmRHB6Zz72OOqkjPKFct4mQiAhU+vTLD8SVyGTyKsuhAtvbaCXV3MI3gCg7txAH42YKHWrlHNPfK7QoM=

    # AWS_REGION for bin/cached-bundle
    - secure: PZCFNxDGbAdMJaKcoGW4YKxBEInIaKo+9Sq/vwb2fkCvhFU3edYHHsAJotzKAZyB/JN4s2tBWBKuFWqZkrAv6O/1vywcVdajNKV3A57IWN9DJKEQBfIvIlo63Qvm4via9XqgS9t5SFXnPIBEpUnHlEGbhW1TJhmLeH+EvtJmpqI=

    # CACHED_BUNDLE_BUCKET for bin/cached-bundle
    - secure: EddB06NYGPKMnxVGVQjXyHVsmY0xS05qie95N1AHly4uHVhmxLDjXEQIF4b+Em060ywyNRayS/V/PSvXAtOtWQ0ZE6Xs21arvzHfokv4I47fZl6j0WJse1HAvTH8JQuUp2waA7Hrwwyh6hfOo05U9IDqTwRcQmgjie452eGngX8=
addons:
  postgresql: 9.3
notifications:
  webhooks:
    urls:
      # Gitter
      - secure: VWPRxXocEV3I02Zqukku0LF5fb2WDL44RxESPmE5+dNOyxSHdtPbR02cHwQoHbv5BX7dEApaSl4qfo2d/XY00sPSzskCPbm0T8+zMZTdtYFyuQu3Mkaxfw7SjxO1tsukl9/n+jNU+JT9AS68GSvtJdakb8h2a1n19gfSyWQueVs=
