---
language: ruby
bundler_args: --without debugger docs production --deployment --jobs=3 --retry=3
before_install:
  - sudo apt-get install libicu-dev
before_script:
  - bin/rake db:create RAILS_ENV=test
script:
  - bin/rake lint
  - bin/rake spec:unit spec:integration
  - bin/rake spec:javascripts
notifications:
  webhooks:
    urls:
      # Gitter
      - secure: VWPRxXocEV3I02Zqukku0LF5fb2WDL44RxESPmE5+dNOyxSHdtPbR02cHwQoHbv5BX7dEApaSl4qfo2d/XY00sPSzskCPbm0T8+zMZTdtYFyuQu3Mkaxfw7SjxO1tsukl9/n+jNU+JT9AS68GSvtJdakb8h2a1n19gfSyWQueVs=
