---
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: vurse_development

test:
  <<: *default
  database: vurse_test

production:
  url: <%= ENV['VURSE_DATABASE_URL'] %>
